ALTER TABLE "config" ADD COLUMN IF NOT EXISTS "cityResellerLimitEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "config" ADD COLUMN IF NOT EXISTS "cityResellerLimitCount" INTEGER NOT NULL DEFAULT 5;
